# Generated by Django 4.1.4 on 2022-12-22 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Map",
        ),
    ]
